apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.spec.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}

    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            # Environment variables from the ConfigMap
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: DB_USER
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: DB_SERVER
            # Environment variables from the Secret
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secret
                  key: API_KEY
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secret
                  key: DB_PASSWORD